blog/app/Http/routes.php
<?php



Route::get('/', function () {
    return Redirect::to('index');
});

Route::any('home', function(){
    return view('/home');       
});


Route::group(['prefix'=>'lk', 'middleware' => 'auth'], function () {
    
	Route::get('exercise', ['as' => 'viewexer', 'uses' => 'ExerciseController@viewExer']);
	Route::get('classrooms', ['as' => 'viewroom', 'uses' => 'ClassroomController@viewRoom']);
	Route::get('childgroup', ['as' => 'viewgroup', 'uses' => 'ChildgroupController@viewGroup']);
	Route::get('teachers', ['as' => 'viewteach', 'uses' => 'UsersController@viewTeach']);
	Route::get('news', ['as' => 'viewnews', 'uses' => 'NewsitemController@viewNews']);

	Route::get('addroom', ['as' => 'addroom', 'uses' => 'ClassroomController@addRoom']);
	Route::get('addgroup', ['as' => 'addgroup', 'uses' => 'ChildgroupController@addGroup']);
	Route::get('addexer', ['as' => 'addexer', 'uses' => 'ExerciseController@addExer']);
	Route::get('addteach', ['as' => 'addteach', 'uses' => 'UsersController@addTeach']);
	Route::get('addnews', ['as' => 'addnews', 'uses' => 'NewsitemController@addNews']);

	Route::get('rooms/edit/{id}',['as' => 'editroom', function($id) {
		$room_item = App\Classroom::find($id);
		return view('lk.editroom')->with('room_item', $room_item);
	}]);
	Route::post('rooms/edit', ['as'=> 'roomedit', 'uses'=>'ClassroomController@postEdit']);
	Route::get('rooms/delete/{id}', 'ClassroomController@postDelete');
	Route::post('room/add', ['as'=> 'roomadd', 'uses'=>'ClassroomController@postNew']);

	Route::get('group/edit/{id}',['as' => 'editgroup', function($id) {
		$group_item = App\Childgroup::find($id);
		return view('lk.editgroup')->with('group_item', $group_item);
	}]);
	Route::post('group/edit', ['as'=> 'groupedit', 'uses'=>'ChildgroupController@postEdit']);
	Route::get('group/delete/{id}', 'ChildgroupController@postDelete');
	Route::post('group/add', ['as'=> 'groupadd', 'uses'=>'ChildgroupController@postNew']);

	Route::get('exer/edit/{id}',['as' => 'editexer', function($id) {
		$exer_item = App\Exercise::find($id);
		$room_list = App\Classroom::all();
		$group_list = App\Childgroup::all();
		$teach_list = App\User::all();
		return view('lk.editexer')->with('exer_item', $exer_item)->with('room_list', $room_list)->with('group_list', $group_list)->with('teach_list', $teach_list);
	}]);
	Route::post('exer/edit', ['as'=> 'exeredit', 'uses'=>'ExerciseController@postEdit']);
	Route::post('exer/add', ['as'=> 'exeradd', 'uses'=>'ExerciseController@postNew']);
	Route::get('exer/delete/{id}', 'ExerciseController@postDelete');

	Route::get('teach/edit/{id}',['as' => 'editteach', function($id) {
		$teach_item = App\User::find($id);
		return view('lk.editteach')->with('teach_item', $teach_item);
	}]);
	Route::post('teach/edit', ['as'=> 'teachedit', 'uses'=>'UsersController@postEdit']);
	Route::post('teach/add', ['as'=> 'teachadd', 'uses'=>'UsersController@postNew']);
	Route::get('teach/delete/{id}', 'UsersController@postDelete');

	Route::get('news/edit/{id}',['as' => 'editnews', function($id) {
		$news_item = App\News::find($id);
		return view('lk.editnews')->with('news_item', $news_item);
	}]);
	Route::post('news/edit', ['as'=> 'newsedit', 'uses'=>'NewsitemController@postEdit']);
	Route::post('news/add', ['as'=> 'newsadd', 'uses'=>'NewsitemController@postNew']);
	Route::get('news/delete/{id}', 'NewsitemController@postDelete');
});

Route::get('teach/getjson', 'UsersController@getTeach');

Route::get('/', function () {
	//$teach_list = App\User::all();
	$teach_list = App\User::where('is_teacher',true)->get();
	return view('main.mainindex')->with('teach_list', $teach_list);
});
    
Route::get('news', ['as' => 'mainnews', 'uses' => 'NewsitemController@index'
]);
    
Route::get('gallery', ['as' => 'maingallery', function () {
	return view('main.maingallery');
}]);
    
Route::get('honors', ['as' => 'mainhonors', 'uses' => 'HonorsitemController@index'
]);
    
Route::get('news/{id}', function ($id) {
	$srv = App\News::find($id);
	return view('main.mainnewsview')->with('news', $srv);
});
    
Route::get('guestbook', ['as' => 'mainguestbook', function () {
	return view('main.mainguestbook');
}]);
    
Route::get('repertoire', ['as' => 'mainrepertoire', function () {
	return view('main.mainrepertoire');
}]);
    
Route::get('byrooms', ['as' => 'byrooms', 'uses' => 'ClassroomController@getExerByRoom']);

Route::get('byrooms/{id}', 'ClassroomController@getExerByRoomId');

Route::get('byteach', ['as' => 'byteach', 'uses' => 'ExerciseController@getExerByTeach']);

Route::get('byteach/{id}', 'ExerciseController@getExerByTeachId');
    
Route::get('bygroups', ['as' => 'bygroups', 'uses' => 'ChildgroupController@getExerByGroup']);

Route::get('404', ['as' => '404', function () {
    return view('404');
}]);

Route::get('bygroups/{id}', 'ChildgroupController@getExerByGroupId');
    
Route::get('setagroop', ['as' => 'mainsetagroop', function () {
	return view('main.mainsetagroop');
}]);
    
Route::get('teachers', ['as' => 'mainteachers', function () {
	return view('main.mainteachers');
}]);
    
Route::get('contacts', ['as' => 'maincontacts', function () {
	return view('main.maincontacts');
}]);
    
Route::get('map', ['as' => 'mainmap', function () {
	return view('main.mainmap');
}]);

Route::auth();

blog/app/Exercise.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Exercise extends Model
{
	use SoftDeletes;


	protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'repeattype', 'accesstype', 'time', 'title', 'desc', 'color', 'user_id', 'childgroup_id', 'classroom_id'
    ];

    public function user() {
        return $this->belongsTo('App\User');
    }
    public function childgroup() {
        return $this->belongsTo('App\Childgroup');
    }
    public function classroom() {
        return $this->belongsTo('App\Classroom');
    }
    public function getChildgroupnameAttribute() {
		//dd($this);
        if ($this->childgroup_id)
//            return "Не работает";
             return $this->childgroup->name . "   (" . $this->childgroup->age . " лет )";
        else
            return "Имя группы неизвестно";
    }
    public function getClassroomnameAttribute() {
        if ($this->classroom_id)
            return $this->classroom->name;
//            return "Не работает";
        else
            return "Аудитория не определена";
    }
    public function getUsernameAttribute() {
        if ($this->user_id)
            return $this->user->fio;
        else
            return "Преподаватель не определен";
    }
}

blog/app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
	use SoftDeletes;

	protected $dates = ['deleted_at'];


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'fio', 'education', 'post', 'picture', 'is_teacher', 'id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function exercises() {
        return $this->hasMany('App\Exercise');
    }
    

	public function getPicAttribute() {
		if (!$this->picture)
			return "user_pic_default.png";
		return $this->picture;
	}
	
	
}

blog/resources/views/main/maincontacts.blade.php
@extends('main.mainlayout')

@section('sidecontent')
            <h1 class="page-header">Контакты</h1>
            <section class="col-sm-9">
                <h2>"АРТиШОК", школа танца</h2>
                <p>г. Иркутск, ул. Ломоносова, 72
                </p>
                <p><strong>тел.: (3952) 969-858</strong></p>
                <p>Электронная почта: <a href="mailto:Boss@artishok-irk.ru">Boss@artishok-irk.ru</a></p>
                <a class="dg-widget-link" href="http://2gis.ru/irkutsk/firm/70000001006417054/center/104.25962799999999,52.26657800000001/zoom/16?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=bigMap">Посмотреть на карте Иркутска</a>
                <div class="dg-widget-link"><a href="http://2gis.ru/irkutsk/center/104.259628,52.266578/zoom/16/routeTab/rsType/bus/to/104.259628,52.266578╎АРТиШОК, центр танца?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=route">Найти проезд до АРТиШОК, центр танца</a></div>
                <script charset="utf-8" src="http://widgets.2gis.com/js/DGWidgetLoader.js"></script>
                <script charset="utf-8">
                    new DGWidgetLoader({
                        "width": 640,
                        "height": 600,
                        "borderColor": "#a3a3a3",
                        "pos": {
                            "lat": 52.26657800000001,
                            "lon": 104.25962799999999,
                            "zoom": 16
                        },
                        "opt": {
                            "city": "irkutsk"
                        },
                        "org": [{
                            "id": "70000001006417054"
                        }]
                    });
                </script>
                <noscript style="color:#c00;font-size:16px;font-weight:bold;">Виджет карты использует JavaScript. Включите его в настройках вашего браузера.</noscript>
            </section>


@endsection

blog/resources/views/main/maingallery.blade.php
@extends('main.mainlayout')


@section('sidecontent')

{!! Html::style('assets/swipebox/swipebox.css') !!}
{!! Html::style('assets/css/style.css') !!}

<h1 class="page-header">Галерея</h1>

<div id="loading"></div>

<div id="gallery" style="margin-left: 45px !important; position: static !important; "></div>

{!! Html::script('assets/swipebox/jquery.swipebox.min.js') !!}
{!! Html::script('assets/js/jquery.loadImage.js') !!}
{!! Html::script('assets/js/script.js') !!}

@endsection

blog/resources/views/main/mainguestbook.blade.php
@extends('main.mainlayout')

@section('sidecontent')
     


@endsection

blog/resources/views/main/mainindex.blade.php
@extends('main.mainlayout')

@section('sidecontent')

    <div class="row">
        <div class="col-sm-8">
            <h1 class="text-left hedr1">«АРТиШОК»</h1>
            <h3 class="text-left hedr2">Детский хореографический ансамбль</h3>
        </div>
        <div class="col-sm-4">
            <a href="/setagroop" class="btn btn-success btn-lg  dancebut">
                Начни танцевать <br />прямо <span>сейчас!</span>
            </a>
            
        </div>
    </div>


    
    <!-- <div class="container">

         <div class="col-sm-9 col-sm-offset-2">
         <h1 class="text-left">«АРТиШОК»</h1>
         </div>
         
         <div class="col-sm-9 col-sm-offset-2">
         <h3 class="text-left">Детский хореографический ансамбль</h3b>
         </div>   
         </div>
       -->
    
    <br>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="img/photo[1].JPG">
                <div class="carousel-caption">
                </div>
            </div>

            <div class="item">
                <img src="img/photo[2].JPG">
                <div class="carousel-caption">
                </div>
            </div>

            <div class="item">
                <img src="img/photo[3].JPG">
                <div class="carousel-caption">
                </div>
            </div>
        </div>
    </div><!-- /.carousel -->

    
    <div class="row mainpanes">
        <div class="col-md-10 col-md-offset-1">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">О нас</a></li>
            <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Достижения</a></li>
            <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Атмосфера</a></li>
            <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Набор</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="home">
                <p> Детский хореографический ансамбль «АРТиШОК» 16 марта 2002 года дебютировал на городском конкурсе «Весенняя капель», с тех пор считает данную дату днем своего рождения. </p>
                <p> Основатель коллектива и его руководитель - ЧАРУШИНА Елена Николаевна.</p> <p> В марте 2012 года нам исполнилось 10 лет! И подводя некоторые итоги, мы понимаем, что достигли определенного уровня в обучении детей искусству танца, соответствующего уровню школы.  Как и в любой школе у нас есть программа обучения, в которой предусмотрены уроки по: классическому, эстрадному и современному танцу, гимнастике, актёрскому мастерству, постановочные и репетиционные уроки по сохранению и развитию репертуара коллектива.</p>
            </div>
            <div role="tabpanel" class="tab-pane" id="profile">
                
                <p>2015 Обладатель Гран-При, Лауреат I, II степени, Дипломант I степени и обладатель специального приза жюри «За костюмы» фестиваля-конкурса в рамках Международного проекта «Сибирь зажигает звезды», г. Красноярск;</p><p>2015 Бронзовый Лауреат Международного конкурса-фестиваля детского и молодежного творчества «Весенние выкрутасы 2015», г. Казань, Республика Татарстан;</p><p>2014 Лауреат II и III степени VII Международного фестиваля-конкурса детского и юношеского творчества «Юные дарования России»;</p><p>2014 Лауреат III степени VII Международного фестиваля-конкурса «ART-прорыв»;</p><p>2015 Лауреат I, III степени XI Всероссийского конкурса детского и юношеского творчества «Москва-Байкальск транзит» г. Байкальск;</p>                
                <p>Лауреат I степени II областного конкурса «Ступеньки к успеху»;</p>
                <p>Победитель конкурса концертных программ «Великая страна – Великая победа»;</p>
                <p></p>
                <p></p>
            </div>
            <div role="tabpanel" class="tab-pane" id="messages">
                <p> Занятия проводят талантливые, опытные и отзывчивые педагоги, основная цель которых,  развить творческий потенциал ребенка, сформировать его активность, самостоятельность, стремление к саморазвитию и творчеству.</p>
                
                <p> Добрая атмосфера внутри коллектива позволяет детям найти много друзей. АРТиШАТ объединяют общие интересы, цели, достижения. Дисциплина, к которой приучены наши дети с первых шагов в танцевальном классе, остается на всю жизнь.</p>
                
                <p> Но наша деятельность не ограничивается  стенами танцевального класса. Совместные празднования Нового года, походы на природу, в кино, музеи, подготовки к концертам, поездки, выступления объединяют  нас. Мы становимся близкими друг другу людьми, друзьями.  Все мы – дети, родители, педагоги становимся одной большой семьей, имя которой АРТиШОК!
                </p>
            </div>
            <div role="tabpanel" class="tab-pane" id="settings">
                <p>  Мы принимаем всех детей. У нас "школа танца", а не "фабрика звезд".</p><p> 

Главная наша задача - развитие ребенка, а не его профессиональная карьера. Желание - это, пожалуй, главный для нас критерий. Но и он не всегда является объективным. Как показывает опыт, у многих наших учеников "аппетит просыпается во время еды".</p><p> 

Ребятишки приходят к нам с 3-х лет (девочки, мальчики). Принимаются в группы подготовительного обучения (по возрасту) на общих условиях.</p><p> 

В 2015 году группы М1 (дети 3 – 4 лет) набирает ГАПШИТЕ Елена Павловна, группы М4 (дети 3-4 лет), M5 (дети 5 – 6 лет) набирает СЕРДЮК Юлия Евгеньевна Красным цветом в расписании выделены группы нового набора</p><p> 

Первые две недели обучения «пробные», форма для занятий свободная. Записаться на «пробные» занятия можно по телефону: 89025689777. Обучение начнется со 2 сентября. ДО ВСТРЕЧИ!!! </p>
            </div>
        </div>  <!-- .tab-content -->
        </div>
    </div> <!-- .mainpanes -->

    <br />

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-sm-5">
                    <script type="text/javascript" src="//vk.com/js/api/openapi.js?122"></script>

                    <!-- VK Widget -->
                    <div id="vk_groups"></div>
                    <script type="text/javascript">
                    VK.Widgets.Group("vk_groups", {mode: 0, width: "340", height: "400", color1: 'FFFFFF', color2: '2B587A', color3: '5B7FA6'}, 94401127);
                    </script>
                    

                </div>

                <div class="col-sm-7">
                    <iframe width="560" height="400" src="https://www.youtube.com/embed/Z-JKV6r17Nc" frameborder="0" allowfullscreen></iframe>
                </div>
                
            </div>
        </div>
    </div>
    
    <br />
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
        <div class="panel-body">
            <h3 class="lobster">Танцевальный лагерь на Байкале!</h3>
            <img style="width: 500px;  float:left; margin: 10px;" src="/img/bay.jpg">
            <p class="text-justify" style="font-size: 16px; margin-top: 10px">УРА!!! ЛЕТО!!! Мы решили, что это лето станет для нас особенным. Впервые организовали танцевальный лагерь на Байкале! Турбаза «Тогот»: вкусная еда, уютные номера, гостеприимные хозяева и очень живописный уголок байкальской природы... Два класса в день по современному танцу от потрясающего педагога Владимира Алешина г. Москва, интереснейший класс по hand-made от Ольги Хайрутдиновой были нашими ежедневными составляющими. Но у нас еще было время сходить в поход, попариться в бане, покататься на банане и отметить пять дней рождений! Мы купались и загорали каждый день, устраивали дискотеки, костры с песнями и играмиВот это получился отдых!!!</p>
            <p class="text-right">
                <a class="btn btn-primary" href="asd">Перейти к новости</a>
            </p>
            

        </div>
    </div>
        </div>
    </div>




    <div class="container marketing">
        <center><h1 style="font-family: 'lobster'">Наши преподаватели</h1></center>
        <div class="col-sm-8 col-sm-offset-2" style="padding: 20px">
           @foreach ($teach_list as $teach_item)
               <div class="col-sm-4">
                   <img src="/img/teach/{{ $teach_item->pic }}" alt="" class="img-circle" width="140" height="140">
                   <h2 class="main_teach_title"><a href="byteach/{{ $teach_item->id }}">{{ $teach_item->fio }}</a></h2>
               </div>
           @endforeach
        </div>   
    </div>
    <!-- Left and right controls -->



    <br />
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-body">

                    <p>Контакты: 664074,  Россия, г. Иркутск,  ул. Ломоносова,72;  Тел: 969-858;  E-mail: Boss@artishok-irk.ru;
                    </p>
                    <p>
                        <b>Разработчик: веб-студия Даниила Моисеева</b>
                    </p>
                    

                    

                </div>
            </div>
        </div>
    </div>



@endsection

blog/resources/views/main/mainnewsview.blade.php
@extends('main.mainlayout') @section('sidecontent')
<main>
    <div class="container col-xs-12">
        <h2>{{ $news->title }}</h2>
        <p><strong>Описание: </strong>{{ $news->body }}</p>
        <img src="{{ $news->picture}}" alt="">
    </div>
</main>
@endsection

blog/resources/views/main/searchbygroups.blade.php
@extends('main.mainlayout') @section('sidecontent')

<h1 class="page-header">Расписание</h1>
<ul class="nav nav-tabs nav-justified round-tab">
    <li role="presentation"><a href="{{ URL::route('byteach') }}">Список преподавателей</a></li>
    <li role="presentation"><a href="{{ URL::route('byrooms') }}">Список аудиторий</a></li>
    <li role="presentation" class="active"><a href="{{ URL::route('bygroups') }}" class="active">Список групп</a></li>
</ul>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title"></h2>
    </div>

    <div class="panel-body row">
        <div class="col-sm-4">
            <div id="teachContainer" class="listContainer">
                <ul class="nav nav-pills nav-stacked">
                    @foreach ($group_list as $group_item)
                    <li data-teach="{{ $group_item->id }}" @if($childgroup->id == $group_item->id) class="active" @endif>
                        <a href="/bygroups/{{ $group_item->id }}">
                             <center>{{ $group_item->name }}</center>
                        </a>
                    </li>

                    @endforeach
                </ul>
            </div>
        </div>
        <div class="col-sm-8">
            <center>
                <h2><span id="childgroupResultEducation">{{ $childgroup->age }} лет</span></h2>
            </center>
            @if ($exer_list->isEmpty() == false)
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Преподаватель</th>
                        <th>Аудитория</th>
                        <th>Название</th>
                        <th>Описание</th>
                        <th>Частота занятий</th>
                        <th>Тип занятий</th>
                        <th>Время</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($exer_list as $exer_item)
                    <tr style="background-color:{{ $exer_item->color }}">
                        <td>{{ $exer_item->username }}</td>
                        <td>{{ $exer_item->classroomname }}</td>
                        <td>{{ $exer_item->title }}</td>
                        <td>{{ $exer_item->desc }}</td>
                        <td>{{ $exer_item->repeattype }}</td>
                        <td>{{ $exer_item->accesstype }}</td>
                        <td>{{ $exer_item->time }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            @endif
        </div>
    </div>
</div>
@endsection

blog/resources/views/main/searchbyrooms.blade.php
@extends('main.mainlayout') @section('sidecontent')

<h1 class="page-header">Расписание</h1>
<ul class="nav nav-tabs nav-justified round-tab">
    <li role="presentation"><a href="{{ URL::route('byteach') }}">Список преподавателей</a></li>
    <li role="presentation" class="active"><a href="{{ URL::route('byrooms') }}">Список аудиторий</a></li>
    <li role="presentation"><a href="{{ URL::route('bygroups') }}">Список групп</a></li>
</ul>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title"></h2>
    </div>
    <div class="panel-body row">
        <div class="col-sm-4">
            <div id="teachContainer" class="listContainer">
                <ul class="nav nav-pills nav-stacked">
                    @foreach ($room_list as $room_item)
                    <li data-teach="{{ $room_item->id }}" @if($classroom->id == $room_item->id) class="active" @endif>
                        <a href="/byrooms/{{ $room_item->id }}">
                            <center>
                                {{ $room_item->name }}</center>
                        </a>
                    </li>

                    @endforeach
                </ul>
            </div>
            <!-- #teachContainer -->
        </div>
        <div class="col-sm-8">
            <center>
                <p><strong>Адрес: </strong><span id="roomResultEducation">{{ $classroom->address }}</span></p>
            </center>
            <img src="{{ $classroom->picture }}" class="leftimg" style="margin: 0px 10px 10px 0;     width: 700px;"> @if ($room_list->isEmpty() == false)
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Преподаватель</th>
                        <th>Название</th>
                        <th>Описание</th>
                        <th>Частота занятий</th>
                        <th>Тип занятий</th>
                        <th>Время</th>
                        <th>Группа</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($exer_list as $exer_item)
                    <tr style="background-color:{{ $exer_item->color }}">
                        <td>{{ $exer_item->username }}</td>
                        <td>{{ $exer_item->title }}</td>
                        <td>{{ $exer_item->desc }}</td>
                        <td>{{ $exer_item->repeattype }}</td>
                        <td>{{ $exer_item->accesstype }}</td>
                        <td>{{ $exer_item->time }}</td>
                        <td>{{ $exer_item->childgroupname }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            @endif
        </div>


    </div>

</div>
@endsection

blog/resources/views/main/searchbyteach.blade.php
@extends('main.mainlayout') @section('sidecontent')

<h1 class="page-header">Расписание</h1>
<ul class="nav nav-tabs nav-justified round-tab">
    <li role="presentation" class="active"><a href="{{ URL::route('byteach') }}">Список преподавателей</a></li>
    <li role="presentation"><a href="{{ URL::route('byrooms') }}">Список аудиторий</a></li>
    <li role="presentation"><a href="{{ URL::route('bygroups') }}">Список групп</a></li>
</ul>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title"></h2>
    </div>
    <div class="panel-body row">
        <div class="col-sm-4">
            <div id="teachContainer" class="listContainer">
                <ul class="nav nav-pills nav-stacked">
                    @foreach ($user_list as $user_item)
                    <li data-teach="{{ $user_item->id }}" @if($teacher->id == $user_item->id) class="active" @endif>
                        <a href="/byteach/{{ $user_item->id }}">
                            <img src="/img/teach/{{ $user_item->pic }}" class="img-circle teachimg_preview">
                             {{ $user_item->fio }}
                        </a>
                    </li>

                    @endforeach
                </ul>
            </div>
            <!-- #teachContainer -->
        </div>
        <div class="col-sm-8">
            <div id="teachResult">
                <img id="teachResultImg" src="/img/teach/{{ $teacher->pic }}" class="teachimg img-rounded">
                <center>
                    <h3 id="teachResultFio">{{ $teacher->fio }}</h3></center>
                <p><strong>Образование: </strong><span id="teachResultEducation">{{ $teacher->education }}</span></p>

                @if ($exer_list->isEmpty() == false)
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Название</th>
                            <th>Описание</th>
                            <th>Аудитория</th>
                            <th>Частота занятий</th>
                            <th>Тип занятий</th>
                            <th>Время</th>
                            <th>Группа</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($exer_list as $exer_item)
                        <tr style="background-color:{{ $exer_item->color }}">
                            <td>{{ $exer_item->title }}</td>
                            <td>{{ $exer_item->desc }}</td>
                            <td>{{ $exer_item->classroomname }}</td>
                            <td>{{ $exer_item->repeattype }}</td>
                            <td>{{ $exer_item->accesstype }}</td>
                            <td>{{ $exer_item->time }}</td>
                            <td>{{ $exer_item->childgroupname }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection